services:
  eews-seeder:
    build:
      context: ./seeder
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-seeder:latest
    env_file:
      - .seeder.env

  eews-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-producer:latest
    env_file:
      - .producer.env

  eews-queue:
    build:
      context: ./queue
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-queue:latest
    env_file:
      - .queue.env

  eews-picker:
    build:
      context: ./picker
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-picker:latest
    env_file:
      - .picker.env

  eews-ml:
    build:
      context: ./machine-learning
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-ml:latest
    env_file:
      - .ml.env

  eews-ws-rest:
    build:
      context: ./ws-rest
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-ws-rest:latest
    env_file:
      - .ws-rest.env

  eews-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-frontend:latest

  demo-eews-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-nginx:latest

  demo-eews-prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-prometheus:latest

  demo-eews-grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/demo-eews-grafana:latest
