version: '3'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - '8000:8080'
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 34.134.231.165:8097
