global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "scrape producer service"
    static_configs:
      - targets: ["demo-eews-producer:8001"]
  - job_name: "scrape queue service"
    static_configs:
      - targets: [ "demo-eews-queue:8002" ]
  - job_name: "scrape picker service"
    static_configs:
      - targets: [ "demo-eews-picker:8003" ]
