# Use the official Grafana image as the base
FROM grafana/grafana:latest

# Copy provisioning files into the Grafana provisioning directory
COPY ./grafana-provisioning /etc/grafana/provisioning

# Expose the default Grafana port
EXPOSE 3000
