services:
  eews-producer:
    build:
      context: ../producer
      dockerfile: Dockerfile
    image: docker.io/slackingdjaeger/main-eews-producer:latest
    env_file:
      - ./secrets/.producer.env