version: '3'
services:
  eews-ml-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eews-ml-1
    env_file:
      - .env
  eews-ml-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eews-ml-2
    env_file:
      - .env
  eews-ml-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eews-ml-3
    env_file:
      - .env
  eews-nginx:
    image: nginx
    container_name: eews-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - eews-ml-1
      - eews-ml-2
      - eews-ml-3
